mail:
  host: MAIL_HOST
  username: MAIL_USERNAME
  password: MAIL_PASSWORD

digests:
  ruby:
    feeds:
      - https://byroot.github.io/feed.xml
      - https://ivoanjo.me/feed.xml
      - https://joel.drapper.me/rss.xml
      - https://kddnewton.com/feed.xml
      - https://noelrappin.com/rss.xml
      - https://railsatscale.com/feed.xml
      - https://rubyweekly.com/rss
      - https://world.hey.com/this.week.in.rails/feed.atom
      - https://hnrss.org/newest?q=Ruby+OR+Rails&points=50
      - https://github.com/rails/rails/commits.atom
      - https://discuss.rubyonrails.org/latest.rss
      - https://us11.campaign-archive.com/feed?u=1aa0f43522f6d9ef96d1c5d6f&id=840412962b
      - https://www.ruby-lang.org/en/feeds/news.rss
      - https://blog.rubygems.org/atom.xml
      - https://www.mikeperham.com/index.xml
      - https://blog.peterzhu.ca/feed.xml
      - https://mensfeld.pl/feed/
      - https://patshaughnessy.net/index.xml
      - https://jpcamara.com/feed.xml
    format:
      - md
    mail:
      format: html
      to:
        - RUBY_DIGEST_RECIPIENT
